In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas 
from shapely.geometry import Point

In [2]:
df = pd.read_csv('teroris.csv', encoding='ISO-8859-1')

C:\Users\Oriza Sativa\AppData\Local\Temp\ipykernel_23836\2542009977.py:1: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('teroris.csv', encoding='ISO-8859-1')

In [3]:
indonesia_data = df[df['country_txt'] == 'Indonesia']
indonesia_data.head(10)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
5571,197711290004,1977,11,29,NaN,0,NaN,93,Indonesia,5,...,NaN,NaN,NaN,NaN,State Department 1997 Document,0,1,1,1,NaN
6340,197805160001,1978,5,16,NaN,0,NaN,93,Indonesia,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,0,-9,NaN
6891,197810200003,1978,10,20,NaN,0,NaN,93,Indonesia,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,0,-9,NaN
13179,198103280001,1981,3,28,NaN,1,3/31/1981,93,Indonesia,5,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
21464,198403260021,1984,3,26,NaN,0,NaN,93,Indonesia,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
24020,198412240004,1984,12,24,NaN,0,NaN,93,Indonesia,5,...,NaN,NaN,NaN,NaN,UMD Miscellaneous,-9,-9,0,-9,NaN
24250,198501210001,1985,1,21,NaN,0,NaN,93,Indonesia,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,0,-9,NaN
24576,198503150001,1985,3,15,NaN,0,NaN,93,Indonesia,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,0,-9,NaN
28044,198605140007,1986,5,14,NaN,0,NaN,93,Indonesia,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
28049,198605140012,1986,5,14,NaN,0,NaN,93,Indonesia,5,...,NaN,NaN,NaN,NaN,PGIS,1,1,1,1,NaN

In [4]:
indonesia_data.shape

(761, 135)

In [5]:
#Basic information

indonesia_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 761 entries, 5571 to 181337
Columns: 135 entries, eventid to related
dtypes: float64(55), int64(22), object(58)
memory usage: 808.6+ KB

In [6]:
missing_values = indonesia_data.isnull().sum()
missing_values

eventid         0
iyear           0
imonth          0
iday            0
approxdate    754
             ...
INT_LOG         0
INT_IDEO        0
INT_MISC        0
INT_ANY         0
related       561
Length: 135, dtype: int64

In [7]:
columns_to_drop = missing_values[missing_values > 533].index
df_clean = indonesia_data.drop(columns=columns_to_drop)
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 761 entries, 5571 to 181337
Data columns (total 64 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   eventid           761 non-null    int64
 1   iyear             761 non-null    int64
 2   imonth            761 non-null    int64
 3   iday              761 non-null    int64
 4   extended          761 non-null    int64
 5   country           761 non-null    int64
 6   country_txt       761 non-null    object
 7   region            761 non-null    int64
 8   region_txt        761 non-null    object
 9   provstate         753 non-null    object
 10  city              752 non-null    object
 11  latitude          744 non-null    float64
 12  longitude         744 non-null    float64
 13  specificity       761 non-null    float64
 14  vicinity          761 non-null    int64
 15  summary           612 non-null    object
 16  crit1             761 non-null    int64
 17  crit2             761 non-null    int64
 18  crit3             761 non-null    int64
 19  doubtterr         760 non-null    float64
 20  multiple          761 non-null    float64
 21  success           761 non-null    int64
 22  suicide           761 non-null    int64
 23  attacktype1       761 non-null    int64
 24  attacktype1_txt   761 non-null    object
 25  targtype1         761 non-null    int64
 26  targtype1_txt     761 non-null    object
 27  targsubtype1      727 non-null    float64
 28  targsubtype1_txt  727 non-null    object
 29  corp1             702 non-null    object
 30  target1           760 non-null    object
 31  natlty1           756 non-null    float64
 32  natlty1_txt       756 non-null    object
 33  gname             761 non-null    object
 34  motive            489 non-null    object
 35  guncertain1       761 non-null    float64
 36  individual        761 non-null    int64
 37  nperps            419 non-null    float64
 38  nperpcap          577 non-null    float64
 39  claimed           612 non-null    float64
 40  weaptype1         761 non-null    int64
 41  weaptype1_txt     761 non-null    object
 42  weapsubtype1      635 non-null    float64
 43  weapsubtype1_txt  635 non-null    object
 44  weapdetail        315 non-null    object
 45  nkill             754 non-null    float64
 46  nkillus           613 non-null    float64
 47  nkillter          606 non-null    float64
 48  nwound            729 non-null    float64
 49  nwoundus          609 non-null    float64
 50  nwoundte          590 non-null    float64
 51  property          761 non-null    int64
 52  propextent        295 non-null    float64
 53  propextent_txt    295 non-null    object
 54  propcomment       234 non-null    object
 55  ishostkid         761 non-null    float64
 56  scite1            612 non-null    object
 57  scite2            400 non-null    object
 58  scite3            245 non-null    object
 59  dbsource          761 non-null    object
 60  INT_LOG           761 non-null    int64
 61  INT_IDEO          761 non-null    int64
 62  INT_MISC          761 non-null    int64
 63  INT_ANY           761 non-null    int64
dtypes: float64(20), int64(22), object(22)
memory usage: 386.4+ KB

In [8]:
columns_txt = [col for col in df_clean.columns if col.endswith('_txt')]
no_txt = [col.replace('_txt', '') for col in columns_txt]
df_clean = df_clean.drop(columns=no_txt)
df_clean.columns

Index(['eventid', 'iyear', 'imonth', 'iday', 'extended', 'country_txt',
       'region_txt', 'provstate', 'city', 'latitude', 'longitude',
       'specificity', 'vicinity', 'summary', 'crit1', 'crit2', 'crit3',
       'doubtterr', 'multiple', 'success', 'suicide', 'attacktype1_txt',
       'targtype1_txt', 'targsubtype1_txt', 'corp1', 'target1', 'natlty1_txt',
       'gname', 'motive', 'guncertain1', 'individual', 'nperps', 'nperpcap',
       'claimed', 'weaptype1_txt', 'weapsubtype1_txt', 'weapdetail', 'nkill',
       'nkillus', 'nkillter', 'nwound', 'nwoundus', 'nwoundte', 'property',
       'propextent_txt', 'propcomment', 'ishostkid', 'scite1', 'scite2',
       'scite3', 'dbsource', 'INT_LOG', 'INT_IDEO', 'INT_MISC', 'INT_ANY'],
      dtype='object')

In [9]:
no_iday = df_clean[df_clean['iday'] == 0].index
df_clean = df_clean.drop(no_iday)
df_clean['date'] = pd.to_datetime(df_clean['iyear'].astype(str) + '-' + df_clean['imonth'].astype(str) + '-' + df_clean['iday'].astype(str))
df_clean = df_clean.drop(columns=['iyear', 'imonth', 'iday'])

columns = df_clean.columns.tolist()
last_column = columns.pop(-1)
columns.insert(1, last_column)
df_clean = df_clean[columns]
pd.set_option('display.max_columns', None)

df_clean.head()

,eventid,date,extended,country_txt,region_txt,provstate,city,latitude,longitude,specificity,vicinity,summary,crit1,crit2,crit3,doubtterr,multiple,success,suicide,attacktype1_txt,targtype1_txt,targsubtype1_txt,corp1,target1,natlty1_txt,gname,motive,guncertain1,individual,nperps,nperpcap,claimed,weaptype1_txt,weapsubtype1_txt,weapdetail,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent_txt,propcomment,ishostkid,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
5571,197711290004,1977-11-29,0,Indonesia,Southeast Asia,North Sumatra,Unknown,3.585242,98.675598,4.0,0,NaN,1,1,1,0.0,0.0,1,0,Armed Assault,Business,Industrial/Textiles/Factory,Bechtel,workers,United States,Free Aceh Movement (GAM),NaN,0.0,0,NaN,NaN,NaN,Firearms,Rifle/Shotgun (non-automatic),Rifles; Machetes,1.0,1.0,0.0,1.0,1.0,0.0,1,NaN,NaN,0.0,NaN,NaN,NaN,State Department 1997 Document,0,1,1,1
6340,197805160001,1978-05-16,0,Indonesia,Southeast Asia,Papua,Unknown,-2.533000,140.717000,4.0,0,NaN,1,1,1,-9.0,0.0,1,0,Hostage Taking (Kidnapping),Government (General),"Government Personnel (excluding police, military)",indonesian govt,senior government officials,Indonesia,Irian Jaya Rebels,NaN,0.0,0,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1.0,NaN,NaN,NaN,PGIS,-9,-9,0,-9
6891,197810200003,1978-10-20,0,Indonesia,Southeast Asia,NaN,Jakarta,-6.208821,106.846046,1.0,0,NaN,1,1,1,0.0,0.0,1,0,Assassination,Government (General),"Government Personnel (excluding police, military)",NaN,official residence of Foreign Minister,Indonesia,Unknown,NaN,0.0,0,10.0,NaN,NaN,Melee,Knife or Other Sharp Object,Knives; Firearms,NaN,NaN,NaN,1.0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,-9,-9,0,-9
13179,198103280001,1981-03-28,1,Indonesia,Southeast Asia,Jakarta,Jakarta,-6.208821,106.846046,1.0,0,NaN,1,1,1,0.0,0.0,1,0,Hijacking,Airports & Aircraft,Aircraft (not at an airport),Airliner- Indonesia Gamda Airlines,NaN,Indonesia,Komando Jihad (Indonesian),NaN,0.0,0,5.0,NaN,NaN,Explosives,Grenade,Grenades; Small caliber,4.0,NaN,4.0,0.0,NaN,NaN,0,NaN,NaN,1.0,NaN,NaN,NaN,PGIS,0,0,0,0
21464,198403260021,1984-03-26,0,Indonesia,Southeast Asia,NaN,Yuroot,-4.346411,138.094482,2.0,1,NaN,1,1,1,-9.0,0.0,1,0,Hostage Taking (Kidnapping),Private Citizens & Property,Labor Union Related,"Associated Mission Aviation, a Roman Catholic *","Vanmere Vider, pilot",Switzerland,Irian Jaya Rebels,NaN,0.0,0,NaN,NaN,NaN,Unknown,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,1.0,NaN,NaN,NaN,PGIS,-9,-9,1,1

In [10]:
df_clean.head(20)

,eventid,date,extended,country_txt,region_txt,provstate,city,latitude,longitude,specificity,vicinity,summary,crit1,crit2,crit3,doubtterr,multiple,success,suicide,attacktype1_txt,targtype1_txt,targsubtype1_txt,corp1,target1,natlty1_txt,gname,motive,guncertain1,individual,nperps,nperpcap,claimed,weaptype1_txt,weapsubtype1_txt,weapdetail,nkill,nkillus,nkillter,nwound,nwoundus,nwoundte,property,propextent_txt,propcomment,ishostkid,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
5571,197711290004,1977-11-29,0,Indonesia,Southeast Asia,North Sumatra,Unknown,3.585242,98.675598,4.0,0,NaN,1,1,1,0.0,0.0,1,0,Armed Assault,Business,Industrial/Textiles/Factory,Bechtel,workers,United States,Free Aceh Movement (GAM),NaN,0.0,0,NaN,NaN,NaN,Firearms,Rifle/Shotgun (non-automatic),Rifles; Machetes,1.0,1.0,0.0,1.0,1.0,0.0,1,NaN,NaN,0.0,NaN,NaN,NaN,State Department 1997 Document,0,1,1,1
6340,197805160001,1978-05-16,0,Indonesia,Southeast Asia,Papua,Unknown,-2.533000,140.717000,4.0,0,NaN,1,1,1,-9.0,0.0,1,0,Hostage Taking (Kidnapping),Government (General),"Government Personnel (excluding police, military)",indonesian govt,senior government officials,Indonesia,Irian Jaya Rebels,NaN,0.0,0,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,1.0,NaN,NaN,NaN,PGIS,-9,-9,0,-9
6891,197810200003,1978-10-20,0,Indonesia,Southeast Asia,NaN,Jakarta,-6.208821,106.846046,1.0,0,NaN,1,1,1,0.0,0.0,1,0,Assassination,Government (General),"Government Personnel (excluding police, military)",NaN,official residence of Foreign Minister,Indonesia,Unknown,NaN,0.0,0,10.0,NaN,NaN,Melee,Knife or Other Sharp Object,Knives; Firearms,NaN,NaN,NaN,1.0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,-9,-9,0,-9
13179,198103280001,1981-03-28,1,Indonesia,Southeast Asia,Jakarta,Jakarta,-6.208821,106.846046,1.0,0,NaN,1,1,1,0.0,0.0,1,0,Hijacking,Airports & Aircraft,Aircraft (not at an airport),Airliner- Indonesia Gamda Airlines,NaN,Indonesia,Komando Jihad (Indonesian),NaN,0.0,0,5.0,NaN,NaN,Explosives,Grenade,Grenades; Small caliber,4.0,NaN,4.0,0.0,NaN,NaN,0,NaN,NaN,1.0,NaN,NaN,NaN,PGIS,0,0,0,0
21464,198403260021,1984-03-26,0,Indonesia,Southeast Asia,NaN,Yuroot,-4.346411,138.094482,2.0,1,NaN,1,1,1,-9.0,0.0,1,0,Hostage Taking (Kidnapping),Private Citizens & Property,Labor Union Related,"Associated Mission Aviation, a Roman Catholic *","Vanmere Vider, pilot",Switzerland,Irian Jaya Rebels,NaN,0.0,0,NaN,NaN,NaN,Unknown,NaN,NaN,2.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,1.0,NaN,NaN,NaN,PGIS,-9,-9,1,1
24020,198412240004,1984-12-24,0,Indonesia,Southeast Asia,NaN,Malang,-7.981894,112.626503,1.0,0,NaN,1,1,1,0.0,0.0,1,0,Bombing/Explosion,Religious Figures/Institutions,Place of Worship,NaN,Catholic Church and Seminary,Indonesia,Unknown,NaN,0.0,0,NaN,NaN,NaN,Explosives,Unknown Explosive Type,Bomb,0.0,0.0,0.0,0.0,0.0,0.0,1,NaN,NaN,0.0,NaN,NaN,NaN,UMD Miscellaneous,-9,-9,0,-9
24250,198501210001,1985-01-21,0,Indonesia,Southeast Asia,Unknown,Unknown,NaN,NaN,5.0,0,NaN,1,1,1,0.0,0.0,1,0,Bombing/Explosion,Religious Figures/Institutions,Place of Worship,NaN,Buddhist temple of Borobudus,Indonesia,Muslim extremists,NaN,0.0,0,NaN,NaN,NaN,Explosives,Unknown Explosive Type,Explosive,0.0,NaN,NaN,0.0,NaN,NaN,1,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,-9,-9,0,-9
24576,198503150001,1985-03-15,0,Indonesia,Southeast Asia,East Java,Banyuwangi,-8.218116,114.367304,1.0,1,NaN,1,1,1,0.0,0.0,1,0,Bombing/Explosion,Transportation,Bus (excluding tourists),NaN,bus carrying 28 passengers from city of Malang...,Indonesia,Unknown,NaN,0.0,0,NaN,NaN,NaN,Explosives,Unknown Explosive Type,Explosive,7.0,NaN,NaN,14.0,NaN,NaN,1,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,-9,-9,0,-9
28044,198605140007,1986-05-14,0,Indonesia,Southeast Asia,Jakarta,Jakarta,-6.208821,106.846046,1.0,0,NaN,1,1,1,0.0,0.0,1,0,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,NaN,Embassy,Canada,Unknown,NaN,0.0,0,NaN,NaN,NaN,Explosives,Vehicle,Explosive,0.0,NaN,NaN,2.0,NaN,NaN,1,NaN,"Damages: explosion, destroyed 2 vehicles and d...",0.0,NaN,NaN,NaN,PGIS,-9,-9,1,1
28049,198605140012,1986-05-14,0,Indonesia,Southeast Asia,Jakarta,Jakarta,-6.208821,106.846046,1.0,0,NaN,1,1,1,0.0,0.0,1,0,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,NaN,Embassy,United States,Anti-Imperialist International Brigades,NaN,0.0,0,NaN,NaN,NaN,Explosives,"Projectile (rockets, mortars, RPGs, etc.)",Rocket,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,1,1,1,1
28050,198605140013,1986-05-14,0,Indonesia,Southeast Asia,Jakarta,Jakarta,-6.208821,106.846046,1.0,0,NaN,1,1,1,0.0,0.0,1,0,Bombing/Explosion,Government (Diplomatic),Embassy/Consulate,NaN,Embassy,Japan,Anti-Imperialist International Brigades,NaN,0.0,0,NaN,NaN,NaN,Explosives,"Projectile (rockets, mortars, RPGs, etc.)",Rocket,0.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,1,1,1,1
28317,198606120007,1986-06-12,0,Indonesia,Southeast Asia,Unknown,Draguigan,NaN,NaN,5.0,0,NaN,1,1,1,0.0,0.0,1,0,Bombing/Explosion,Tourists,Other Facility,NaN,tourist center,Indonesia,Commandos of France,NaN,0.0,0,NaN,NaN,NaN,Explosives,Unknown Explosive Type,Explosive,0.0,NaN,NaN,0.0,NaN,NaN,1,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,1,1,0,1
36759,198901010008,1989-01-01,0,Indonesia,Southeast Asia,East Timor,Dili,-8.549660,125.566599,1.0,0,NaN,1,1,0,1.0,0.0,1,0,Bombing/Explosion,Military,Military Barracks/Base/Headquarters/Checkpost,military,ammunition dump,Indonesia,Revolutionary Front for an Independent East Ti...,NaN,0.0,0,NaN,NaN,NaN,Explosives,Unknown Explosive Type,Explosive,84.0,NaN,0.0,27.0,NaN,0.0,1,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,0,0,0,0
39874,198909260013,1989-09-26,0,Indonesia,Southeast Asia,Aceh,Unknown,4.707828,96.732788,4.0,0,NaN,1,1,0,1.0,0.0,1,0,Armed Assault,Military,Military Barracks/Base/Headquarters/Checkpost,Military,Post,Indonesia,Free Aceh Movement (GAM),NaN,0.0,0,NaN,NaN,NaN,Firearms,Automatic or Semi-Automatic Rifle,Automatic firearm,1.0,NaN,NaN,0.0,NaN,NaN,1,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,0,0,0,0
42729,199005310014,1990-05-31,0,Indonesia,Southeast Asia,Aceh,Unknown,4.707828,96.732788,4.0,0,NaN,1,1,0,1.0,0.0,1,0,Assassination,Military,"Military Personnel (soldiers, troops, officers...",Military,"2 soldiers, one child",Indonesia,Unknown,NaN,0.0,0,NaN,NaN,NaN,Firearms,Automatic or Semi-Automatic Rifle,Automatic firearm,3.0,NaN,NaN,0.0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,-9,-9,0,-9
43137,199006300001,1990-06-30,0,Indonesia,Southeast Asia,Aceh,Unknown,4.707828,96.732788,4.0,0,NaN,1,1,1,-9.0,0.0,1,0,Armed Assault,Business,Industrial/Textiles/Factory,NaN,Logging Truck,Indonesia,Unknown,NaN,0.0,0,NaN,NaN,NaN,Incendiary,NaN,Incendiary,2.0,NaN,NaN,0.0,NaN,NaN,1,Minor (likely < $1 million),NaN,0.0,NaN,NaN,NaN,PGIS,-9,-9,0,-9
43138,199006300002,1990-06-30,0,Indonesia,Southeast Asia,Aceh,Unknown,4.707828,96.732788,4.0,0,NaN,1,1,1,-9.0,0.0,1,0,Armed Assault,Government (General),Government Building/Facility/Office,Govt,State Plantation Firm Minibus,Indonesia,Unknown,NaN,0.0,0,NaN,NaN,NaN,Firearms,Automatic or Semi-Automatic Rifle,Automatic firearm,7.0,NaN,NaN,0.0,NaN,NaN,1,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,-9,-9,0,-9
45180,199101180013,1991-01-18,0,Indonesia,Southeast Asia,Jakarta,Jakarta,-6.208821,106.846046,1.0,0,NaN,1,1,1,0.0,0.0,0,0,Assassination,Government (Diplomatic),"Diplomatic Personnel (outside of embassy, cons...",U.S. State Dept.,"residence compound, U.S. Ambassador John Monjo",United States,Unknown,NaN,0.0,0,NaN,NaN,NaN,Explosives,Unknown Explosive Type,Explosive - defused,0.0,NaN,NaN,0.0,NaN,NaN,1,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,-9,-9,1,1
45616,199102200007,1991-02-20,0,Indonesia,Southeast Asia,Unknown,Unknown,NaN,NaN,5.0,0,NaN,1,1,1,0.0,0.0,1,0,Bombing/Explosion,Utilities,Oil,Caltex (combine of Texaco and Chevron),Duri oil field,Indonesia,Unknown,NaN,0.0,0,NaN,NaN,NaN,Explosives,Unknown Explosive Type,Explosive,0.0,NaN,NaN,60.0,NaN,NaN,1,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,-9,-9,1,1
46025,199104050003,1991-04-05,0,Indonesia,Southeast Asia,Aceh,Banda Aceh,5.541471,95.342957,1.0,0,NaN,1,1,1,0.0,0.0,1,0,Assassination,Police,Police Security Forces/Officers,Police,"residence, Police Chief Colonel Sahwan",Indonesia,Free Aceh Movement (GAM),NaN,0.0,0,NaN,NaN,NaN,Explosives,Unknown Explosive Type,Explosive,1.0,NaN,NaN,0.0,NaN,NaN,1,NaN,NaN,0.0,NaN,NaN,NaN,PGIS,0,0,0,0

In [11]:
df_clean = df_clean.drop(columns=['nwoundte', 'suicide', 'multiple', 'specificity', 'vicinity', 'doubtterr', 'summary', 'crit1', 'crit2', 'crit3', 'guncertain1', 'claimed', 'nperps', 'nperpcap', 'scite1', 'scite2', 'dbsource', 'motive', 'country_txt', 'region_txt','weapdetail'])
df_clean.isnull().sum()

eventid               0
date                  0
extended              0
provstate             7
city                  9
latitude             17
longitude            17
success               0
attacktype1_txt       0
targtype1_txt         0
targsubtype1_txt     34
corp1                59
target1               1
natlty1_txt           5
gname                 0
individual            0
weaptype1_txt         0
weapsubtype1_txt    125
nkill                 7
nkillus             147
nkillter            154
nwound               32
nwoundus            151
property              0
propextent_txt      465
propcomment         526
ishostkid             0
scite3              515
INT_LOG               0
INT_IDEO              0
INT_MISC              0
INT_ANY               0
dtype: int64

In [12]:
# replave missing value with object type ('no info')
df_clean[['targsubtype1_txt', 'corp1', 'weapsubtype1_txt']] = df_clean[['targsubtype1_txt', 'corp1', 'weapsubtype1_txt']].fillna('Unknown')
# replave missing value with object type (-9)
df_clean[['nkillus', 'nkill', 'nkillter', 'nwound', 'nwoundus']] = df_clean[['nkillus', 'nkill', 'nkillter', 'nwound', 'nwoundus']].fillna(-9)
# delete missing value with object type
df_clean = df_clean.dropna(subset=['target1', 'natlty1_txt', 'ishostkid'])
# delete missing value with float type
df_clean = df_clean.dropna(subset=['latitude', 'longitude'])

df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 738 entries, 5571 to 181337
Data columns (total 32 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   eventid           738 non-null    int64
 1   date              738 non-null    datetime64[ns]
 2   extended          738 non-null    int64
 3   provstate         731 non-null    object
 4   city              729 non-null    object
 5   latitude          738 non-null    float64
 6   longitude         738 non-null    float64
 7   success           738 non-null    int64
 8   attacktype1_txt   738 non-null    object
 9   targtype1_txt     738 non-null    object
 10  targsubtype1_txt  738 non-null    object
 11  corp1             738 non-null    object
 12  target1           738 non-null    object
 13  natlty1_txt       738 non-null    object
 14  gname             738 non-null    object
 15  individual        738 non-null    int64
 16  weaptype1_txt     738 non-null    object
 17  weapsubtype1_txt  738 non-null    object
 18  nkill             738 non-null    float64
 19  nkillus           738 non-null    float64
 20  nkillter          738 non-null    float64
 21  nwound            738 non-null    float64
 22  nwoundus          738 non-null    float64
 23  property          738 non-null    int64
 24  propextent_txt    290 non-null    object
 25  propcomment       232 non-null    object
 26  ishostkid         738 non-null    float64
 27  scite3            243 non-null    object
 28  INT_LOG           738 non-null    int64
 29  INT_IDEO          738 non-null    int64
 30  INT_MISC          738 non-null    int64
 31  INT_ANY           738 non-null    int64
dtypes: datetime64[ns](1), float64(8), int64(9), object(14)
memory usage: 190.3+ KB

In [13]:
df_clean[['extended', 'individual', 'property', 'ishostkid', 'INT_LOG', 'INT_IDEO', 'INT_MISC', 'INT_ANY']] = df_clean[['extended', 'individual', 'property', 'ishostkid', 'INT_LOG', 'INT_IDEO', 'INT_MISC', 'INT_ANY']].replace({0: 'no', 1: 'yes', -9: 'unknown'})
df_clean[['nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus']] = df_clean[['nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus']].replace(-9, 0)
df_clean.head()

,eventid,date,extended,provstate,city,latitude,longitude,success,attacktype1_txt,targtype1_txt,targsubtype1_txt,corp1,target1,natlty1_txt,gname,individual,weaptype1_txt,weapsubtype1_txt,nkill,nkillus,nkillter,nwound,nwoundus,property,propextent_txt,propcomment,ishostkid,scite3,INT_LOG,INT_IDEO,INT_MISC,INT_ANY
5571,197711290004,1977-11-29,no,North Sumatra,Unknown,3.585242,98.675598,1,Armed Assault,Business,Industrial/Textiles/Factory,Bechtel,workers,United States,Free Aceh Movement (GAM),no,Firearms,Rifle/Shotgun (non-automatic),1.0,1.0,0.0,1.0,1.0,yes,NaN,NaN,no,NaN,no,yes,yes,yes
6340,197805160001,1978-05-16,no,Papua,Unknown,-2.533000,140.717000,1,Hostage Taking (Kidnapping),Government (General),"Government Personnel (excluding police, military)",indonesian govt,senior government officials,Indonesia,Irian Jaya Rebels,no,Unknown,Unknown,0.0,0.0,0.0,0.0,0.0,no,NaN,NaN,yes,NaN,unknown,unknown,no,unknown
6891,197810200003,1978-10-20,no,NaN,Jakarta,-6.208821,106.846046,1,Assassination,Government (General),"Government Personnel (excluding police, military)",Unknown,official residence of Foreign Minister,Indonesia,Unknown,no,Melee,Knife or Other Sharp Object,0.0,0.0,0.0,1.0,0.0,no,NaN,NaN,no,NaN,unknown,unknown,no,unknown
21464,198403260021,1984-03-26,no,NaN,Yuroot,-4.346411,138.094482,1,Hostage Taking (Kidnapping),Private Citizens & Property,Labor Union Related,"Associated Mission Aviation, a Roman Catholic *","Vanmere Vider, pilot",Switzerland,Irian Jaya Rebels,no,Unknown,Unknown,2.0,0.0,0.0,0.0,0.0,no,NaN,NaN,yes,NaN,unknown,unknown,yes,yes
24020,198412240004,1984-12-24,no,NaN,Malang,-7.981894,112.626503,1,Bombing/Explosion,Religious Figures/Institutions,Place of Worship,Unknown,Catholic Church and Seminary,Indonesia,Unknown,no,Explosives,Unknown Explosive Type,0.0,0.0,0.0,0.0,0.0,yes,NaN,NaN,no,NaN,unknown,unknown,no,unknown

In [ ]:
df_clean.head(20)

In [14]:
df_clean.drop(['INT_LOG', 'INT_IDEO','INT_MISC','INT_ANY', 'scite3', 'ishostkid', 'propcomment', 'propextent_txt', 'property', 'nwoundus', 'nwound', 'nkillter', 'nkillus', 'weapsubtype1_txt', 'individual', 'gname', 'natlty1_txt', 'target1', 'corp1', 'targsubtype1_txt', 'extended'], axis=1, inplace=True)

In [15]:
df_clean.shape

(738, 11)

In [16]:
df_clean.duplicated().sum()

0

In [ ]:
df_clean

In [17]:
fp = 'C:/Intern/idn_adm_bps_20200401_shp/idn_admbnda_adm1_bps_20200401.shp'
map_df = geopandas.read_file(fp)

In [18]:
# Select relevant columns
data = df_clean[['eventid','latitude', 'longitude','date','attacktype1_txt','targtype1_txt','weaptype1_txt','nkill']]

In [19]:
gdf = geopandas.GeoDataFrame(
    data, geometry=geopandas.points_from_xy(data.longitude, data.latitude), crs="EPSG:4326"
)

In [20]:
gdf['PROVINCE'] = ''
for idx in range(map_df.shape[0]):
    # For every address, find if they reside within a province
    pip = gdf.within(map_df.loc[idx, 'geometry'])
    if pip.sum() > 0: 
        # If some of the addresses reside at map_df.loc[idx]
        province = map_df.loc[idx, 'ADM1_EN']
        gdf.loc[pip, 'PROVINCE'] = province

# Drop rows where 'PROVINCE' is empty
gdf = gdf[gdf['PROVINCE'] != '']

In [21]:
def scoring_attack_type(score_attack):
    if score_attack in ['Hostage Taking (Barricade Incident)', 'Unarmed Assault','Hostage Taking (Kidnapping)', 'Unknown']:
        return int(1)
    if score_attack in ['Facility/Infrastructure Attack', 'Hijacking']:
        return int(2)
    if score_attack in ['Armed Assault', 'Bombing/Explosion', 'Assassination']:
        return int(3)

def scoring_targ_type(score_targ):
    if score_targ in ['Religious Figures/Institutions', 'Educational Institution', 'NGO', 'Business', 'Journalists & Media', 'Terrorists/Non-State Militia', 'Violent Political Party', 'Unknown']:
        return int(1)
    if score_targ in ['Airports & Aircraft', 'Transportation', 'Utilities', 'Maritime', 'Private Citizens & Property', 'Tourists', 'Food or Water Supply']:
        return int(2)
    if score_targ in ['Government (General)', 'Military', 'Government (Diplomatic)', 'Police']:
        return int(3)

def scoring_weap_type(score_weap):
    if score_weap in ['Melee', 'Unknown', 'Other']:
        return int(1)
    if score_weap in ['Incendiary', 'Chemical']:
        return int(2)
    if score_weap in ['Firearms', 'Explosives']:
        return int(3)

def scoring_nkill(score_nkill):
    if score_nkill in range(0, 6):
        return int(1)
    if score_nkill in range(5, 20):
        return int(2)
    if score_nkill in range(20,110):
        return int(3)

def alert_level(alert_score):
    if alert_score in range(3, 7):
        return 'Low Level'
    if alert_score in range(6, 10):
        return 'Medium Level'
    if alert_score in range(9, 13):
        return 'High Level'

In [22]:
gdf['Attack Score'] = gdf['attacktype1_txt'].apply(scoring_attack_type)
gdf['Target Score'] = gdf['targtype1_txt'].apply(scoring_targ_type)
gdf['Weap Score'] = gdf['weaptype1_txt'].apply(scoring_weap_type)
gdf['Kill Score'] = gdf['nkill'].apply(scoring_nkill)
gdf['Threat Score'] = gdf['Attack Score'] + gdf['Target Score'] + gdf['Weap Score'] + gdf['Kill Score']
gdf['Alert Level'] = gdf['Threat Score'].apply(alert_level)

In [23]:
gdf

,eventid,latitude,longitude,date,attacktype1_txt,targtype1_txt,weaptype1_txt,nkill,geometry,PROVINCE,Attack Score,Target Score,Weap Score,Kill Score,Threat Score,Alert Level
5571,197711290004,3.585242,98.675598,1977-11-29,Armed Assault,Business,Firearms,1.0,POINT (98.67560 3.58524),Sumatera Utara,3,1,3,1,8,Medium Level
6340,197805160001,-2.533000,140.717000,1978-05-16,Hostage Taking (Kidnapping),Government (General),Unknown,0.0,POINT (140.71700 -2.53300),Papua,1,3,1,1,6,Low Level
6891,197810200003,-6.208821,106.846046,1978-10-20,Assassination,Government (General),Melee,0.0,POINT (106.84605 -6.20882),Dki Jakarta,3,3,1,1,8,Medium Level
21464,198403260021,-4.346411,138.094482,1984-03-26,Hostage Taking (Kidnapping),Private Citizens & Property,Unknown,2.0,POINT (138.09448 -4.34641),Papua,1,2,1,1,5,Low Level
24020,198412240004,-7.981894,112.626503,1984-12-24,Bombing/Explosion,Religious Figures/Institutions,Explosives,0.0,POINT (112.62650 -7.98189),Jawa Timur,3,1,3,1,8,Medium Level
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180427,201711120029,-4.457827,137.122554,2017-11-12,Armed Assault,Business,Firearms,0.0,POINT (137.12255 -4.45783),Papua,3,1,3,1,8,Medium Level
180491,201711140027,-4.333184,136.999194,2017-11-14,Armed Assault,Business,Firearms,0.0,POINT (136.99919 -4.33318),Papua,3,1,3,1,8,Medium Level
180513,201711150026,-4.457827,137.122554,2017-11-15,Armed Assault,Police,Firearms,1.0,POINT (137.12255 -4.45783),Papua,3,3,3,1,10,High Level
181240,201712110030,-7.221500,112.732927,2017-12-11,Bombing/Explosion,Unknown,Explosives,0.0,POINT (112.73293 -7.22150),Jawa Timur,3,1,3,1,8,Medium Level
181337,201712150025,-4.693395,139.364375,2017-12-15,Armed Assault,Business,Firearms,1.0,POINT (139.36437 -4.69339),Papua,3,1,3,1,8,Medium Level

In [ ]:
gdf.sort_values(by='nkill', ascending=False)

In [24]:
gdf.describe()

,eventid,latitude,longitude,date,nkill,Attack Score,Target Score,Weap Score,Kill Score,Threat Score
count,6.720000e+02,672.000000,672.000000,672,672.000000,672.000000,672.000000,672.00000,672.000000,672.000000
mean,2.004509e+11,-1.563695,111.945015,2005-01-05 00:57:51.428571392,1.407738,2.696429,1.994048,2.65625,1.053571,8.400298
min,1.977113e+11,-10.180151,95.246036,1977-11-29 00:00:00,0.000000,1.000000,1.000000,1.00000,1.000000,4.000000
25%,2.000093e+11,-6.208821,97.607574,2000-09-26 12:00:00,0.000000,3.000000,1.000000,2.00000,1.000000,8.000000
50%,2.002021e+11,-2.538018,106.934551,2002-02-12 12:00:00,0.000000,3.000000,2.000000,3.00000,1.000000,8.000000
75%,2.012055e+11,4.527142,120.754749,2012-05-30 12:00:00,1.000000,3.000000,3.000000,3.00000,1.000000,10.000000
max,2.017122e+11,5.550000,140.993510,2017-12-15 00:00:00,101.000000,3.000000,3.000000,3.00000,3.000000,11.000000
std,7.297222e+08,4.950269,14.347553,NaN,6.254451,0.612915,0.861476,0.63386,0.250399,1.527356

In [25]:
# Drop columns from gdf
columns_to_drop = ['latitude', 'longitude', 'geometry', 'Attack Score', 'Target Score', 'Weap Score', 'Kill Score', 'Threat Score']
gdf.drop(columns=columns_to_drop, inplace=True)

# Save to CSV
gdf.to_csv('Terrorist.csv', index=False)

**Exploratory Data Analysis**

In [ ]:
# Counting the number of incidents per province
location_incident_count = gdf['PROVINCE'].value_counts()

# Plotting
plt.figure(figsize=(10, 6))
ax = location_incident_count.head(10).plot(kind='bar', color='skyblue')
plt.title('Top 10 Province by Number of Incidents')
plt.xlabel('Province')
plt.ylabel('Number of Incidents')
plt.xticks(rotation=45)
for p in ax.patches:
    ax.annotate(str(p.get_height()), (p.get_x() * 1.005, p.get_height() * 1.005))
plt.tight_layout()
plt.show()

In [ ]:
# Calculate success rate for each location
success_rate = gdf.groupby('PROVINCE')['success'].mean()

# Plotting success rate
plt.figure(figsize=(10, 6))
ax2 = success_rate.loc[location_incident_count.head(10).index].plot(kind='bar', color='green')
plt.title('Success Rate in Top 10 Locations')
plt.xlabel('Location')
plt.ylabel('Success Rate')
plt.xticks(rotation=45)
for p in ax2.patches:
    ax2.annotate(f'{p.get_height():.2f}', (p.get_x() * 1.005, p.get_height() * 1.005))

plt.tight_layout()
plt.show()

In [ ]:
# Examining the trend of incidents over the years
gdf['year'] = pd.to_datetime(gdf['date']).dt.year
yearly_incident_count = gdf['year'].value_counts().sort_index()

# Plotting
plt.figure(figsize=(10, 6))
ax = yearly_incident_count.plot(kind='line', marker='o', linestyle='-', color='red')
plt.title('Number of Incidents Over the Years')
plt.xlabel('Year')
plt.ylabel('Number of Incidents')
for i, label in enumerate(list(yearly_incident_count.index)):
    score = yearly_incident_count[label]
    plt.annotate(score, (label, score), textcoords="offset points", xytext=(0,10), ha='center')
plt.tight_layout()
plt.show()

In [ ]:
# Calculate success rate for each location
success_rate = gdf.groupby('year')['success'].mean()

# Plotting success rate
plt.figure(figsize=(10, 6))
ax2 = success_rate.loc[yearly_incident_count.index].plot(kind='line', marker='o', linestyle='-', color='red')
plt.title('Success Rate of Incidents Over the Years')
plt.xlabel('Year')
plt.ylabel('Success Rate')
plt.xticks(rotation=45)
for p in ax2.patches:
    ax2.annotate(f'{p.get_height():.2f}', (p.get_x() * 1.005, p.get_height() * 1.005))

plt.tight_layout()
plt.show()

In [ ]:
# Attack Type Analysis: Determining the most common types of attacks
attack_type_count = gdf['attacktype1_txt'].value_counts()

# Plotting
plt.figure(figsize=(10, 6))
ax = attack_type_count.plot(kind='bar', color='green')
plt.title('Most Common Types of Attacks')
plt.xlabel('Type of Attack')
plt.ylabel('Number of Incidents')
plt.xticks(rotation=45)
for p in ax.patches:
    ax.annotate(str(p.get_height()), (p.get_x() * 1.005, p.get_height() * 1.005))
plt.tight_layout()
plt.show()

In [ ]:
# Calculate success rate for each location
success_rate = gdf.groupby('attacktype1_txt')['success'].mean()

# Plotting success rate
plt.figure(figsize=(10, 6))
ax2 = success_rate.loc[attack_type_count.head(10).index].plot(kind='bar', color='green')
plt.title('Success Rate in Most Common Types of Attacks')
plt.xlabel('Type of Attack')
plt.ylabel('Success Rate')
plt.xticks(rotation=45)
for p in ax2.patches:
    ax2.annotate(f'{p.get_height():.2f}', (p.get_x() * 1.005, p.get_height() * 1.005))

plt.tight_layout()
plt.show()

In [ ]:
# Target Type Analysis: Identifying the most frequent targets of attacks
target_type_count = gdf['targtype1_txt'].value_counts()

# Plotting
plt.figure(figsize=(10, 6))
ax = target_type_count.plot(kind='bar', color='orange')
plt.title('Most Frequently Targeted Types')
plt.xlabel('Type of Target')
plt.ylabel('Number of Incidents')
plt.xticks(rotation=45)
for p in ax.patches:
    ax.annotate(str(p.get_height()), (p.get_x() * 1.005, p.get_height() * 1.005))
plt.tight_layout()
plt.show()

In [ ]:
# Calculate success rate for each location
success_rate = gdf.groupby('targtype1_txt')['success'].mean()

# Plotting success rate
plt.figure(figsize=(10, 6))
ax2 = success_rate.loc[target_type_count.head(10).index].plot(kind='bar', color='green')
plt.title('Most Frequently Targeted Types')
plt.xlabel('Type of Target')
plt.ylabel('Success Rate')
plt.xticks(rotation=45)
for p in ax2.patches:
    ax2.annotate(f'{p.get_height():.2f}', (p.get_x() * 1.005, p.get_height() * 1.005))

plt.tight_layout()
plt.show()

In [ ]:
# Grouping by location and alert level, and counting occurrences
alert_level_counts = gdf.groupby(['PROVINCE', 'Alert Level']).size().unstack(fill_value=0)

# Sorting locations based on total incident count
location_incident_count = gdf['PROVINCE'].value_counts()
top_locations = location_incident_count.head(10).index

# Selecting only the top locations for plotting
alert_level_counts_top = alert_level_counts.loc[top_locations]

# Plotting
plt.figure(figsize=(10, 6))
alert_level_counts_top.plot(kind='bar', stacked=True)
plt.title('Distribution of Alert Levels in Top 10 Locations')
plt.xlabel('Location')
plt.ylabel('Number of Incidents')
plt.xticks(rotation=45)
plt.legend(title='Alert Level')
plt.tight_layout()
plt.show()

In [ ]:
fig, ax = plt.subplots(figsize=(15,15))
map_df.plot(ax=ax, alpha=0.4, color='grey')
gdf[gdf['Alert Level'] == 'High Level'].plot(ax=ax, color='red', markersize=5, label='High Level')
gdf[gdf['Alert Level'] == 'Medium Level'].plot(ax=ax, color='orange', markersize=5, label='Medium Level')
gdf[gdf['Alert Level'] == 'Low Level'].plot(ax=ax, color='yellow', markersize=5, label='Low Level')
#plt.legend(prop={'size':15})

# Adjust plot limits to ensure a valid aspect ratio
ax.set_xlim(gdf.total_bounds[0], gdf.total_bounds[2])
ax.set_ylim(gdf.total_bounds[1], gdf.total_bounds[3])

plt.title('Locations Colored by Alert Level')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.legend()
plt.show()

In [ ]:
# Splitting the data in three shows some spatial clustering around the center
gdf.plot(column="Alert Level", cmap="OrRd", edgecolor="k", legend=True)